### ISSUE TITLE
Add links to donation page and remove placeholder content

### ISSUE THREAD

**Issue by otech47** [blockchainedu/benweb#3]
### Donation Options
- Paypal
- Shapeshift
- 6 QR code public addresses
-- BTC
-- BTC (Segwit)
-- ETH
-- LTC
-- LTC Segwit
-- BCH

@Jinglan I'm just going to wing it to adapt the existing Donate page (https://www.blockchainedu.org/donate/) with the new Fury template styles but if there's anything specific you're looking for in the design, feel free to drop a comment

**Comment by Jinglan** [comment]
No, that's perfect. The paypal donation email address is jing@blockchainedu.org
